######################################################################
# Automatically generated by qmake (2.01a) lun. mars 2 17:06:58 2015
######################################################################

QT += gui widgets sql

TEMPLATE = app
TARGET = SQLAppMVC
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    connect.cpp \
    fenetre.cpp \
    mytextedit.cpp

HEADERS += \
    connect.h \
    fenetre.h \
    mytextedit.h
